/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* Access reducer*/

export const GET_ADMIN_LIST = "GET_ADMIN_LIST";
export const GET_ADMIN_LIST_SUCCESS = "GET_ADMIN_LIST_SUCCESS";
export const GET_ADMIN_LIST_ERROR = "GET_ADMIN_LIST_ERROR";
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'

/* Communication reducer*/

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR'
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR'

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_ERROR = 'ADD_NOTIFICATION_ERROR';
export const EDIT_NOTIFICATION = 'EDIT_NOTIFICATION';
export const EDIT_NOTIFICATION_SUCCESS = 'EDIT_NOTIFICATION_SUCCESS';
export const EDIT_NOTIFICATION_ERROR = 'EDIT_NOTIFICATION_ERROR'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR';
export const GET_CATEGORIE_SUCCESS = "GET_CATEGORIE_SUCCESS";
export const GET_CATEGORIE_ERROR = "GET_CATEGORIE_ERROR";
export const GET_CATEGORIE = "GET_CATEGORIE";


export const GET_COMMUNICATIONS = "GET_COMMUNICATIONS";
export const GET_COMMUNICATIONS_SUCCESS = "GET_COMMUNICATIONS_SUCCESS";
export const GET_COMMUNICATIONS_ERROR = "GET_COMMUNICATIONS_ERROR";
export const GET_COMMUNICATION = "GET_COMMUNICATION";
export const GET_COMMUNICATION_SUCCESS = "GET_COMMUNICATION_SUCCESS";
export const GET_COMMUNICATION_ERROR = "GET_COMMUNICATION_ERROR";
export const ADD_COMMUNICATION = 'ADD_COMMUNICATION';
export const ADD_COMMUNICATION_SUCCESS = 'ADD_COMMUNICATION_SUCCESS';
export const ADD_COMMUNICATION_ERROR = 'ADD_COMMUNICATION_ERROR';
export const EDIT_COMMUNICATION = 'EDIT_COMMUNICATION';
export const EDIT_COMMUNICATION_SUCCESS = 'EDIT_COMMUNICATION_SUCCESS';
export const EDIT_COMMUNICATION_ERROR = 'EDIT_COMMUNICATION_ERROR'
export const DELETE_COMMUNICATION = 'DELETE_COMMUNICATION';
export const DELETE_COMMUNICATION_SUCCESS = 'DELETE_COMMUNICATION_SUCCESS';
export const DELETE_COMMUNICATION_ERROR = 'DELETE_COMMUNICATION_ERROR';
export const PUBLISH_COMMUNICATION = 'PUBLISH_COMMUNICATION';
export const PUBLISH_COMMUNICATION_SUCCESS = 'PUBLISH_COMMUNICATION_SUCCESS';
export const PUBLISH_COMMUNICATION_ERROR = 'PUBLISH_COMMUNICATION_ERROR';
export const NOTIFY_COMMUNICATION = 'NOTIFY_COMMUNICATION';
export const NOTIFY_COMMUNICATION_SUCCESS = 'NOTIFY_COMMUNICATION_SUCCESS';
export const NOTIFY_COMMUNICATION_ERROR = 'NOTIFY_COMMUNICATION_ERROR';

export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_ERROR = "GET_EVENTS_ERROR";
export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_ERROR = "GET_EVENT_ERROR";
export const ADD_EVENT = 'ADD_EVENT';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_ERROR = 'ADD_EVENT_ERROR';
export const EDIT_EVENT= 'EDIT_EVENT';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR'
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';
export const DISTRUCT = 'DISTRUCT';

export const GET_SECTIONS = "GET_SECTIONS";
export const GET_SECTIONS_SUCCESS = "GET_SECTIONS_SUCCESS";
export const GET_SECTIONS_ERROR = "GET_SECTIONS_ERROR";
export const GET_SECTION = "GET_SECTION";
export const GET_SECTION_SUCCESS = "GET_SECTION_SUCCESS";
export const GET_SECTION_ERROR = "GET_SECTION_ERROR";
export const ADD_SECTION = 'ADD_SECTION';
export const ADD_SECTION_SUCCESS = 'ADD_SECTION_SUCCESS';
export const ADD_SECTION_ERROR = 'ADD_SECTION_ERROR';
export const EDIT_SECTION = 'EDIT_SECTION';
export const EDIT_SECTION_SUCCESS = 'EDIT_SECTION_SUCCESS';
export const EDIT_SECTION_ERROR = 'EDIT_SECTION_ERROR'
export const DELETE_SECTION = 'DELETE_SECTION';
export const DELETE_SECTION_SUCCESS = 'DELETE_SECTION_SUCCESS';
export const DELETE_SECTION_ERROR = 'DELETE_SECTION_ERROR'

export const GET_SUB_SECTIONS = "GET_SUB_SECTIONS";
export const GET_SUB_SECTIONS_SUCCESS = "GET_SUB_SECTIONS_SUCCESS";
export const GET_SUB_SECTIONS_ERROR = "GET_SUB_SECTIONS_ERROR";
export const GET_SUB_SECTION = "GET_SUB_SECTION";
export const GET_SUB_SECTION_SUCCESS = "GET_SUB_SECTION_SUCCESS";
export const GET_SUB_SECTION_ERROR = "GET_SUB_SECTION_ERROR";
export const ADD_SUB_SECTION = 'ADD_SUB_SECTION';
export const ADD_SUB_SECTION_SUCCESS = 'ADD_SUB_SECTION_SUCCESS';
export const ADD_SUB_SECTION_ERROR = 'ADD_SUB_SECTION_ERROR';
export const EDIT_SUB_SECTION = 'EDIT_SUB_SECTION';
export const EDIT_SUB_SECTION_SUCCESS = 'EDIT_SUB_SECTION_SUCCESS';
export const EDIT_SUB_SECTION_ERROR = 'EDIT_SUB_SECTION_ERROR'
export const DELETE_SUB_SECTION = 'DELETE_SUB_SECTION';
export const DELETE_SUB_SECTION_SUCCESS = 'DELETE_SUB_SECTION_SUCCESS';
export const DELETE_SUB_SECTION_ERROR = 'DELETE_SUB_SECTION_ERROR'


export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";
export const GET_QUESTION = "GET_QUESTION";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR = "GET_QUESTION_ERROR";
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const EDIT_QUESTION_ERROR = 'EDIT_QUESTION_ERROR'
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR'


export const GET_SURVEYS = "GET_SURVEYS";
export const GET_SURVEYS_SUCCESS = "GET_SURVEYS_SUCCESS";
export const GET_SURVEYS_ERROR = "GET_SURVEYS_ERROR";
export const GET_SURVEY = "GET_SURVEY";
export const GET_SURVEY_SUCCESS = "GET_SURVEY_SUCCESS";
export const GET_SURVEY_ERROR = "GET_SURVEY_ERROR";
export const ADD_SURVEY = 'ADD_SURVEY';
export const ADD_SURVEY_SUCCESS = 'ADD_SURVEY_SUCCESS';
export const ADD_SURVEY_ERROR = 'ADD_SURVEY_ERROR';
export const EDIT_SURVEY = 'EDIT_SURVEY';
export const EDIT_SURVEY_SUCCESS = 'EDIT_SURVEY_SUCCESS';
export const EDIT_SURVEY_ERROR = 'EDIT_SURVEY_ERROR'
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS';
export const DELETE_SURVEY_ERROR = 'DELETE_SURVEY_ERROR'
export const PUBLISH_SURVEY = 'PUBLISH_SURVEY';
export const PUBLISH_SURVEY_SUCCESS = 'PUBLISH_SURVEY_SUCCESS';
export const PUBLISH_SURVEY_ERROR = 'PUBLISH_SURVEY_ERROR'
export const NOTIFY_SURVEY = 'NOTIFY_SURVEY';
export const NOTIFY_SURVEY_SUCCESS = 'NOTIFY_SURVEY_SUCCESS';
export const NOTIFY_SURVEY_ERROR = 'NOTIFY_SURVEY_ERROR'
export const GET_SURVEY_RESULT = 'GET_SURVEY_RESULT';
export const GET_SURVEY_RESULT_SUCCESS = 'GET_SURVEY_RESULT_SUCCESS';
export const GET_SURVEY_RESULT_ERROR = 'GET_SURVEY_RESULT_ERROR'

/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/* CHAT APP*/
export const CHAT_GET_CONTACTS = "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS = "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR = "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS = "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS = "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR = "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION = "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT = "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION = "CHAT_CHANGE_CONVERSATION";

/* SURVEY LIST APP*/
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const SURVEY_LIST_GET_LIST_SUCCESS = "SURVEY_LIST_GET_LIST_SUCCESS";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  "SURVEY_LIST_GET_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  "SURVEY_LIST_SELECTED_ITEMS_CHANGE";

/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";

export const GET_COUNT_COMM = "GET_COUNT_COMM"
export const GET_COUNT_COMM_SUCCESS = "GET_COUNT_COMM_SUCCESS"
export const GET_COUNT_COMM_ERROR = "GET_COUNT_COMM_ERROR"
export const GET_COUNT_FAQ = "GET_COUNT_FAQ"
export const GET_COUNT_FAQ_SUCCESS = "GET_COUNT_FAQ_SUCCESS"
export const GET_COUNT_FAQ_ERROR = "GET_COUNT_FAQ_ERROR"
export const GET_COUNT_EVENT = "GET_COUNT_EVENT"
export const GET_COUNT_EVENT_SUCCESS = "GET_COUNT_EVENT_SUCCESS"
export const GET_COUNT_EVENT_ERROR = "GET_COUNT_EVENT_ERROR"
export const GET_COUNT_USER = "GET_COUNT_EVENT"
export const GET_COUNT_USER_SUCCESS = "GET_COUNT_USER_SUCCESS"
export const GET_COUNT_USER_ERROR = "GET_COUNT_USER_ERROR"
export const GET_COUNT_SURVEY = "GET_COUNT_EVENT"
export const GET_COUNT_SURVEY_SUCCESS = "GET_COUNT_SURVEY_SUCCESS"
export const GET_COUNT_SURVEY_ERROR = "GET_COUNT_SURVEY_ERROR"

export const GET_ARTICLE_VIEWD = "GET_ARTICLE_VIEWD"
export const GET_ARTICLE_VIEWD_SUCCESS = "GET_ARTICLE_VIEWD_SUCCESS"
export const GET_ARTICLE_VIEWD_ERROR = "GET_ARTICLE_VIEWD_ERROR"

export const GET_ARTICLE_LIKED = "GET_ARTICLE_LIKED"
export const GET_ARTICLE_LIKED_SUCCESS = "GET_ARTICLE_LIKED_SUCCESS"
export const GET_ARTICLE_LIKED_ERROR = "GET_ARTICLE_LIKED_ERROR"

export const GET_ARTICLE_SADED = "GET_ARTICLE_SADED"
export const GET_ARTICLE_SADED_SUCCESS = "GET_ARTICLE_SADED_SUCCESS"
export const GET_ARTICLE_SADED_ERROR = "GET_ARTICLE_SADED_ERROR"



export const GET_EVENT_VIEWD = "GET_EVENT_VIEWD"
export const GET_EVENT_VIEWD_SUCCESS = "GET_EVENT_VIEWD_SUCCESS"
export const GET_EVENT_VIEWD_ERROR = "GET_EVENT_VIEWD_ERROR"

export const GET_EVENT_LIKED = "GET_EVENT_LIKED"
export const GET_EVENT_LIKED_SUCCESS = "GET_EVENT_LIKED_SUCCESS"
export const GET_EVENT_LIKED_ERROR = "GET_EVENT_LIKED_ERROR"

export const GET_EVENT_SADED = "GET_EVENT_SADED"
export const GET_EVENT_SADED_SUCCESS = "GET_EVENT_SADED_SUCCESS"
export const GET_EVENT_SADED_ERROR = "GET_EVENT_SADED_ERROR"

export const GET_EVENT_PARTICIPED = "GET_EVENT_PARTICIPED"
export const GET_EVENT_PARTICIPED_SUCCESS = "GET_EVENT_PARTICIPED_SUCCESS"
export const GET_EVENT_PARTICIPED_ERROR = "GET_EVENT_PARTICIPED_ERROR"

export const GET_FAQ_FAVOR = "GET_FAQ_FAVOR"
export const GET_FAQ_FAVOR_SUCCESS = "GET_FAQ_FAVOR_SUCCESS"
export const GET_FAQ_FAVOR_ERROR = "GET_FAQ_FAVOR_ERROR"

export const GET_USER_EVENT_PARTICIPATED = "GET_USER_EVENT_PARTICIPATED"
export const GET_USER_EVENT_PARTICIPATED_SUCCESS = "GET_USER_EVENT_PARTICIPATED_SUCCESS"
export const GET_USER_EVENT_PARTICIPATED_ERROR = "GET_USER_EVENT_PARTICIPATED_ERROR"

export const GET_USER_EVENT_VIEW = "GET_USER_EVENT_VIEW"
export const GET_USER_EVENT_VIEW_SUCCESS = "GET_USER_EVENT_VIEW_SUCCESS"
export const GET_USER_EVENT_VIEW_ERROR = "GET_USER_EVENT_VIEW_ERROR"


export const GET_USER_COMM_VIEW = "GET_USER_COMM_VIEW"
export const GET_USER_COMM_VIEW_SUCCESS = "GET_USER_COMM_VIEW_SUCCESS"
export const GET_USER_COMM_VIEW_ERROR = "GET_USER_COMM_VIEW_ERROR"



export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./todo/actions";
export * from "./chat/actions";
export * from "./surveyList/actions";
export * from "./surveyDetail/actions";
